name: Daily SSL Check

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  ssl_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install requests library

      - name: Run SSL Check
        run: |
          python ssl_check.py


# name: SSL Expiry Check

# on:
#   schedule:
#     - cron: "*/5 * * * *" # Every 5 minutes
#   workflow_dispatch:

# jobs:
#   ssl_check:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Bash
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Run SSL Check
#         run: bash .github/scripts/ssl-check.sh
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#           DOMAIN_LIST: ${{ secrets.DOMAIN_LIST }}
